---
- name:Install Nginx
  apt:
    name=nginx state=present update_cache=yes
  when:
    ansible_os_family == "Debian"
  notify:
   - Nginx Systemd

- name: Delete default HTML files
  shell: /bin/rm -rf /usr/share/nginx/html/*.html
# tasks file for nginx
